### ISSUE TITLE
About sample number on human36m.

### ISSUE THREAD

**Issue by Naive-Bayes** [QitaoZhao/ContextAware-PoseFormer#11]
Hi Qitao, thanks for your work on comparing image-base method and lifting method.

I wonder know how many samples you have used on human36m experiment about single-frame?
I find the number of samples in 'h36m_validation.pkl' you provided is 543,344, and  1,559,752 in 'h36m_train.pkl'.
I want to know do you use all samples in training and validation? If not, how to downsample in your exp?

Thanks!

**Comment by QitaoZhao** [comment]
Thanks for your comments! We use all samples from each file for training/testing. If you want to downsample the data, you can look at [here](https://github.com/QitaoZhao/ContextAware-PoseFormer/blob/a2456578e8cd25f9fd99dacdf81d2e3623ca127b/ContextPose/mvn/datasets/human36m.py#L131C14-L131C20) where you can manually reduce the number of samples.

**Comment by Naive-Bayes** [comment]
> Thanks for your comments! We use all samples from each file for training/testing. If you want to downsample the data, you can look at [here](https://github.com/QitaoZhao/ContextAware-PoseFormer/blob/a2456578e8cd25f9fd99dacdf81d2e3623ca127b/ContextPose/mvn/datasets/human36m.py#L131C14-L131C20) where you can manually reduce the number of samples.

Thanks for your answer! Now, I know that. Thank you again.
