### ISSUE TITLE
A question about keypoints

### ISSUE THREAD

**Issue by 124518** [QitaoZhao/ContextAware-PoseFormer#13]
Are keypoints_2d_cpn and keypoints_2d_cpn_crop respectively representing the keypoints detected on the original image and the keypoints after cropping?

**Comment by QitaoZhao** [comment]
Hi, `keypoints_2d_cpn` is the normalized keypoints in the original image, and `keypoints_2d_cpn_crop` is the keypoints after cropping. You can look at the following code we use to pre-process them. (with slightly different names)
https://github.com/QitaoZhao/ContextAware-PoseFormer/blob/a2456578e8cd25f9fd99dacdf81d2e3623ca127b/H36M-Toolbox/generate_labels_h36m.py#L179-L186
