### ISSUE TITLE
Questions about HRNet detected keypoints 2d in the provided files "h36m_train.pkl" and "h36m_validation.pkl"

### ISSUE THREAD

**Issue by wangzhidi** [QitaoZhao/ContextAware-PoseFormer#4]
Thanks for your contributions to the 3D HPE! Could you please tell me how you get the "joints_2d_hrnet" in the "h36m_train.pkl" and "h36m_validation.pkl"? Are there any codes I can refer to?

**Comment by QitaoZhao** [comment]
Please refer to https://github.com/QitaoZhao/ContextAware-PoseFormer?tab=readme-ov-file#dataset-preparation for the code to prepare the data. Also, check here ([link](https://drive.google.com/drive/folders/1OYKWnu_5GPLRfceD3Psf4-JZkloBodKx?usp=sharing)), where I attached my pre-processed data if you don't want to run the code yourself.

**Comment by zerowing-ex** [comment]
I have the same issue, and I'm also curious about how you obtained the 2D keypoints detected by HRNet in 'joints_2d_hrnet' in h36m_train/validation.pkl. There doesn't seem to be relevant content in your code. For example, if you have an image from Human3.6M, it is usually cropped to a suitable size (288*384). The shape should be (1,3,384,288) when input to HRNetw32/48, and the output heatmaps have a shape of (1,17,96,72). Using these heatmaps, you can estimate the 2D pose, but the estimated 2D keypoints are in COCO format, which is different from the format in Human3.6M.
How did you address this issue? Even after converting it to the Human3.6M format, there seems to be a significant difference from the 2D keypoints you provided.
![image](https://github.com/QitaoZhao/ContextAware-PoseFormer/assets/55009709/4dcbe09d-b85e-4f5c-9860-0de5f50573a3)
Note:
the green points are 2D ground truth
the red points are predicated by the HRNet
the orange points are provided HRNet keypoints in the h36m_train/validation.pkl

the green rect is the bbox provided in the h36m_train/validation.pkl
the red rect is the bbox of cropped image (288*384)

**Comment by zerowing-ex** [comment]
I have addressed this problem, thanks for your excellent works again!
![003C03A5](https://github.com/QitaoZhao/ContextAware-PoseFormer/assets/55009709/7799ec7c-af0f-4d00-983e-0a2bb0bc6b3a)

**Comment by QitaoZhao** [comment]
Sorry for the late reply. We do not use the **2D keypoint** from HRNet (we only use the backbone) to report our results. `joints_2d_hrnet` was used for our initial experiments. We do not process HRNet ourselves and only use the pre-processed keypoints from other repos. Currently, I find it hard to provide the source, but I will post it here as soon as I see it.

**Comment by zerowing-ex** [comment]
Thanks!

**Comment by QitaoZhao** [comment]
@zerowing-ex @wangzhidi Please look at https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/TRAINING.md, in my best impression, our pre-processed HRNet keypoints were adopted from `twoDPose_HRN_train.npy` and `twoDPose_HRN_test.npy`.

**Comment by glee623** [comment]
Thank you for your awesome work!

I thought the **output keypoint from the HRNet** was used to get the **Pose Feature P.** 
But at the code, you guys are using **'joints_2d_cpn'** for the coordinate embedding. 
Also, you said **you did not use the 2D keypoint from HRNet**.

Would you explain more about this?
Thanks.

**Comment by zerowing-ex** [comment]
Yes, you're right.
