### ISSUE TITLE
Data loading speed

### ISSUE THREAD

**Issue by Zhenghongwei0929** [QitaoZhao/ContextAware-PoseFormer#5]
Thanks for your excellent work. Currently, data loads are stuck after every k iteration, where k is related to the number of num_workers I set for the data loader. I have tried this problem on different servers. May I ask what causes it?

**Comment by QitaoZhao** [comment]
Thanks for your comments! We did not encounter this issue, and what do you mean by "stuck"? Did training completely stop or something?

**Comment by Zhenghongwei0929** [comment]
Thanks for your replying! The training can still go on but it costs too much time for loading data every k iterations. I have checked that it is caused by the dataloader. But my server has abundant CPU and memory resources.

**Comment by Zhenghongwei0929** [comment]
This is how long it takes for each iteration to load data.
![image](https://github.com/QitaoZhao/ContextAware-PoseFormer/assets/61260733/1600b104-0c4c-4579-bb10-979c9943441c)

**Comment by QitaoZhao** [comment]
Could you please provide a code snippet that produces these statistics (as well as the setting for training if you made any modifications)? I may try to look into this issue and check if this is the case for me.

**Comment by Zhenghongwei0929** [comment]
I didn't change any code; I just counted the time taken for each iteration of next(batch). I noticed that I just now according to  the guidance dealing with data in the H36M-Toolbox, not according to the ContextPose/MVN/datasets/human36m_preprocessing the steps in processing data, whether this will have effect? Thanks again for your reply!

**Comment by QitaoZhao** [comment]
We used the images produced by H36M-Toolbox but made some modifications to the original script to generate labels. Please follow our code to generate the labels! Actually, we also provided our pre-processed labels [here](https://drive.google.com/drive/folders/1OYKWnu_5GPLRfceD3Psf4-JZkloBodKx), you can try to use them.

**Comment by Zhenghongwei0929** [comment]
THX! I will try to process the data using the script in human36m_preprocessing.

**Comment by DeepZheng** [comment]
Have you already solved this problem? I also encountered this issue, and I generated the labels using the author's script.

**Comment by Zhenghongwei0929** [comment]
No, I still haven't solved this problem.
