### ISSUE TITLE
cpn50_256x192.pth.tar

### ISSUE THREAD

**Issue by luxinyi7** [QitaoZhao/ContextAware-PoseFormer#8]
Thanks for your awesome work. Could you share the file ‘data/pretrained/coco/CPN50_256x192.pth.tar ’ or provide a download link?
I would be very glad if you could help me.

**Comment by QitaoZhao** [comment]
You can check this link https://github.com/GengDavid/pytorch-cpn?tab=readme-ov-file#pre-trained-models
