### ISSUE TITLE
Train/val on MPI-INF-3DHP

### ISSUE THREAD

**Issue by DeepZheng** [QitaoZhao/ContextAware-PoseFormer#9]
Thank you for your excellent work! I wonder if you would be willing to share the train/val dataloader for MPI-INF-3DHP. 
Thank you in advance for considering my request.

**Comment by QitaoZhao** [comment]
Thanks for your comments. I would like to do this recently, but no guarantees, sorry. You can indeed start by looking at our scripts to process Human3.6M [[link](https://github.com/QitaoZhao/ContextAware-PoseFormer/blob/main/H36M-Toolbox/generate_labels_h36m.py)], and we roughly followed the same procedure for MPI-INF-3DHP. 

Apologize again!

**Comment by DeepZheng** [comment]
Thank you for your response. I understand the situation you are facing and appreciate your guidance. I will begin by reviewing the script and see how I can proceed from there.

Thanks all the same for your excellent work!

**Comment by QitaoZhao** [comment]
I Apologize for being late. It really took more than I expected. You can check [here](https://github.com/QitaoZhao/ContextAware-PoseFormer/tree/main/ContextPose_mpi) for MPI-INF-3DHP.

**Comment by DeepZheng** [comment]
Thank you once again for your dedication and contributions! Look forward to your future works and research outcomes.
